spin_manifest_version = 2

[application]
name = "urmanac-com"
version = "0.2.0"
authors = ["Kingdon Barrett <kingdon@urmanac.com>"]
description = "Urbit Encyclopedia Root Domain"

[[trigger.http]]
route = "/..."
component = "redirect-root"

[component.redirect-root]
source = { url = "https://github.com/urmanac/spin-redirect/releases/download/v0.2.0/redirect.wasm", digest = "sha256:0e5330a7828b683161823e7a528958009a3753e03aa4dcaf9824015c47f7ea8e" }
environment = { DESTINATION = "https://www.urmanac.com", INCLUDE_PATH = "true", STATUSCODE = "302" }
