spin_manifest_version = 2

[application]
name = "urmanac-com"
version = "0.1.0"
authors = ["Kingdon Barrett <kingdon@urmanac.com>"]
description = "Urbit Encyclopedia Root Domain"

[[trigger.http]]
route = "/..."
component = "redirect-root"

[component.redirect-root]
source = { url = "https://github.com/fermyon/spin-redirect/releases/download/v0.1.0/redirect.wasm", digest = "sha256:8bee959843f28fef2a02164f5840477db81d350877e1c22cb524f41363468e52" }
environment = { DESTINATION = "https://www.urmanac.com", STATUSCODE = "302" }
